export default {
    EMPTY_GAME: {
        _id: '',

        name: '',
        profile1: '',
        profile2: '',
        winner: '',
        startTime: '',
        profile1EndTime: '',
        profile2EndTime: '',
        profile1Path: [0],
        profile2Path: [0],
        startTrack: 0,
        endTrack: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    EMPTY_TRACK: {
        index: '',
        name: '',
        genres: '',
        artist: '',
        album: '',
        image: '',
        preview: '',
        danceability: 0,
        energy: 0,
        loudness: 0,
        speechiness: 0,
        acousticness: 0,
        instrumentalness: 0,
        liveness: 0,
        valence: 0,
        tempo: 0,
        popularity: 0,
        albumReleaseDate: '',
    },
    EMPTY_PROFILE: {
        _id: '',
        username: '',
        activeGame: '',
        games: [],
    },
    EMPTY_GLOBAL_STATE: {
        profile_id: '',
    },
    EMPTY_RES: {
        status: 0,
        success: false,
        data: undefined,
        errorMessage: 'This is the initial response message',
    },

    HOSTED_AT: 'https://mhacks-1fa15c2d64bb.herokuapp.com',

    // SERVER_URL: 'https://beck-six.vercel.app',
    SERVER_URL: 'http://localhost:4000',

    BRIGHT_PINK: '#FF00BC',
} 